### ISSUE TITLE
qca-nss-clients Compile error！

### ISSUE THREAD

**Issue by zxlhhyccc** [bitthief/openwrt#5]
![image](https://user-images.githubusercontent.com/45259624/183949594-920bb005-4783-4944-b1a7-b83898611aad.png)

**Comment by smaller09** [comment]
`  LD [M]  /swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.o
  CC [M]  /swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/pppoe/nss_connmgr_pppoe.o
  LD [M]  /swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/pppoe/qca-nss-pppoe.o
  MODPOST /swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/Module.symvers
ERROR: modpost: "nss_vlan_tx_vsi_detach_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_vlan_tx_add_tag_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_vlan_tx_set_mac_addr_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_unregister_vlan_if" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_vlan_tx_vsi_attach_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_register_vlan_if" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_vlan_tx_set_mtu_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/vlan/qca-nss-vlan.ko] undefined!
ERROR: modpost: "nss_bridge_tx_set_mac_addr_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/bridge/qca-nss-bridge-mgr.ko] undefined!
ERROR: modpost: "nss_bridge_tx_vsi_unassign_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/bridge/qca-nss-bridge-mgr.ko] undefined!
ERROR: modpost: "nss_bridge_tx_vsi_assign_msg" [/swap/AX6/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-ipq807x_generic/qca-nss-clients-2022-03-18-a93764b6/bridge/qca-nss-bridge-mgr.ko] undefined!
WARNING: modpost: suppressed 6 unresolved symbol warnings because there were too many)
`
same here.

**Comment by smaller09** [comment]
I found the solution. 
`
diff --git a/qca/qca-nss-drv/Makefile b/qca/qca-nss-drv/Makefile
index a0b979e..323c8f4 100644
--- a/qca/qca-nss-drv/Makefile
+++ b/qca/qca-nss-drv/Makefile
@@ -57,7 +57,7 @@ EXTRA_CFLAGS+= -I$(STAGING_DIR)/usr/include/qca-nss-gmac \
 
 ifneq (, $(findstring $(CONFIG_TARGET_BOARD), "ipq807x" "ipq60xx"))
 EXTRA_CFLAGS+= -DNSS_MEM_PROFILE_MEDIUM
-LOW_MEM_PROFILE_MAKE_OPTS=y
+#LOW_MEM_PROFILE_MAKE_OPTS=y
 endif
 
 ifeq ($(CONFIG_KERNEL_SKB_FIXED_SIZE_2K),y)
`

**Comment by larrynz** [comment]
I can get to compile without the nss bridge and vlan manager.

The above fix didn't work for me. It still errors out on missing
qca-nss-vlan.ko
